resources:
 - deployment.yml
 - service.yml 
 - configmap.yml
patches:
 - patches/replica_count.yaml
 - patches/resource_limits.yaml
 - patches/env.yaml
#configMapGenerator:
#patchesStrategicMerge:
#images:
#namespace: test
