bases:
  - ../../base
namespace: prod
#patches:
#  - replica_count.yaml
#  - resource_limits.yml
#  - devdbconf.yml
configMapGenerator:
  - name: myapp-xyz-config
    files:
     - configs/app.json
patchesStrategicMerge:
  - env.yml
  - replica_count.yaml
  - dbconf.yml
  - namespace.yml
