apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mying-rule
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /app1
          backend:
            serviceName: app1-svc
            servicePort: 80
        - path: /app2
          backend:
            serviceName: app2-svc
            servicePort: 80
        - path: /app3
          backend:
            serviceName: app3-svc
            servicePort: 80
